# Generated by Django 4.0.2 on 2022-02-26 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('auditorium_id', models.AutoField(auto_created=True, db_column='Auditorium ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Auditorium ID')),
                ('auditorium_name', models.CharField(db_column='Auditorium name', db_index=True, max_length=20, verbose_name='Auditorium name')),
                ('building_name', models.CharField(db_column='Event building', max_length=20, verbose_name='Event place')),
                ('capacity', models.IntegerField(db_column='Capacity', verbose_name='Max capacity of auditorium')),
            ],
        ),
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('place_id', models.AutoField(auto_created=True, db_column='Place ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Place ID')),
                ('street', models.CharField(db_column='Street', max_length=100, verbose_name='Building street')),
                ('city', models.CharField(db_column='Event city', max_length=20, verbose_name='Event city')),
                ('pincode', models.IntegerField(db_column='Pincode', verbose_name='pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(auto_created=True, db_column='Event ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Event ID')),
                ('event_name', models.CharField(db_column='Event Name', db_index=True, max_length=20, verbose_name='Event Name')),
                ('event_summary', models.CharField(db_column='Event Summary', max_length=255, verbose_name='Event Summary')),
                ('event_date_time', models.DateTimeField(db_column='Event Date Time', verbose_name='Event Date Time')),
                ('event_price', models.DecimalField(db_column='Event Price', decimal_places=2, max_digits=7, verbose_name='Event Price')),
                ('event_auditorium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.auditorium')),
                ('event_created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventsMeta',
            fields=[
                ('event_meta_id', models.AutoField(db_column='Event Meta ID', db_index=True, primary_key=True, serialize=False)),
                ('event_duration', models.IntegerField(db_column='Event Duration', verbose_name='Event duration (secs)')),
                ('event_booking_start', models.DateTimeField(blank=True, db_column='Booking start time', null=True, verbose_name='Event booking start Date and time')),
                ('event_booking_end', models.DateTimeField(blank=True, db_column='Booking end time', null=True, verbose_name='Event booking end date')),
                ('max_capacity', models.IntegerField(db_column='Event capacity', default=0, verbose_name='Event max capacity')),
                ('curr_avail', models.IntegerField(db_column='Event availability', verbose_name='current availability')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(auto_created=True, db_column='Place ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Place ID')),
                ('street', models.CharField(db_column='Street', max_length=100, verbose_name='Building street')),
                ('city', models.CharField(db_column='Event city', max_length=20, verbose_name='Event city')),
                ('pincode', models.IntegerField(db_column='Pincode', verbose_name='pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(auto_created=True, db_column='Auditorium ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Auditorium ID')),
                ('Ticket no', models.CharField(max_length=10, unique=True)),
                ('payment_method', models.CharField(db_column='Payment method', max_length=10, verbose_name='Mode of payment')),
                ('amount', models.DecimalField(db_column='Ticket price', decimal_places=2, max_digits=7, verbose_name='Amount payable')),
                ('events', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('ticket_issue_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='event_meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.eventsmeta'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='place',
            field=models.ForeignKey(db_column='Place', on_delete=django.db.models.deletion.CASCADE, to='api.eventplace'),
        ),
    ]
