# Generated by Django 4.0.2 on 2022-02-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='place',
            field=models.ForeignKey(db_column='Place', on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
        migrations.DeleteModel(
            name='EventPlace',
        ),
    ]
