# Generated by Django 4.0.2 on 2022-02-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_auditorium_place_delete_eventplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_auditorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditorium'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
