# Generated by Django 4.0.2 on 2022-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_events_event_auditorium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Ticket no',
            new_name='ticket_no',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(db_column='Ticket no', max_length=10, unique=True),
        ),
    ]
