# Generated by Django 4.0.2 on 2022-02-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_ticket_issue_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events'),
        ),
    ]
