# Generated by Django 4.0.2 on 2022-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ticket_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(auto_created=True, db_column='Ticket ID', db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Ticket ID'),
        ),
    ]
