# Generated by Django 3.0 on 2022-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='booked_till',
            field=models.DateTimeField(blank=True, db_column='Auditorium booked till', null=True),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='is_booked',
            field=models.BooleanField(blank=True, db_column='Auditorium already booked', null=True),
        ),
    ]
